services: 
  - type: web
    name: backend-athlete-tracker
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js   # <-- change here
    envVars:
      - key: NODE_ENV
        value: production
